# Este archivo permite a Render auto-configurar tu proyecto cuando enlaces tu cuenta de GitHub
services:
  - type: web
    name: civis-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    # Render comprobará este endpoint para verificar que el contenedor se levantó correctamente
    healthCheckPath: /health-check
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      
      # Estas variables debes llenarlas manualmente desde el Panel de Render 
      # por motivos de seguridad (No se sincronizarán mediante Git)
      - key: DATABASE_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_API_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
