server {
    listen 0.0.0.0:${PORT} default_server;
    listen [::]:${PORT} default_server;
    server_name _;
    root /var/www/app/public;
    index index.php index.html;

    client_max_body_size 100M;
    underscores_in_headers on;

    # ==================== LOGS ====================
    access_log /dev/stdout;
    error_log /dev/stderr;

    # ==================== HEALTH CHECK ====================
    location /health-check {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # ==================== CORS SETTINGS ====================
    # El archivo cors.php de Laravel se encargará de esto dinámicamente según el .env

    # ==================== STATIC FILES / API ====================
    location / {


        try_files $uri $uri/ /index.php?$query_string;
    }

    # Assets con CORS y Cache
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        add_header 'Access-Control-Allow-Origin' '*' always;
        expires 7d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    # ==================== PHP-FPM ====================
    location ~ \.php$ {
        # FastCGI Config (Using Unix Socket)
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param HTTP_X_XSRF_TOKEN $http_x_xsrf_token;

        # Timeouts y Buffers
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }

    # Seguridad
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
